global:
  registry: ghcr.io
  imageProject: 1000jours

app:
  ~needs: [build-app]
  imagePackage: app
  containerPort: 8080

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        buildOptions: --single-snapshot --ignore-path=/product_uuid --compressed-caching=false # optim for local builds
        buildArgs:
          GITHUB_SHA: "{{ $.Values.global.sha }}"
