name: Preproduction

on:
  push:
    branches: [master]

concurrency:
  group: preproduction
  cancel-in-progress: true

jobs:

  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops to deploy review branch
      uses: SocialGouv/actions/autodevops-helm@v1
      with:
        environment: preprod
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        kubeconfig: ${{ secrets.KUBECONFIG }}
        imageName: fabrique/${{ env.project }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
